 //using hostname.

//[code language="java"]
node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/saurabh0010/sample-spring-microservices.git', CredentialsID: 'github', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('account-service') {
                def app = docker.build "likithc/account-service:${env.version}"
             withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'likithc', passwordVariable: 'Djsnake@12')])
             {
              sh 'echo "Djsnake@12" | docker login -u "likithc" --password-stdin'
                app.push()
              app.push('latest')}
            }
        }

        stage ('Run') {
            docker.image("likithc/account-service:${env.version}").run('-p 2222:2222 -h account --name account --link discovery')
        }

        stage ('Final') {
            build job: 'customer-service-pipeline', wait: false
        }      

    }

}
